townteki/townsquare

- package-lock.json
- package.json
- server/lobby.js
- townsquare-deck-helper/DeckValidator.js
- townsquare-deck-helper/RestrictedList.js
- townsquare-deck-helper/formatDeckAsFullCards.js
- townsquare-deck-helper/formatDeckAsShortCards.js
- townsquare-deck-helper/index.js
Not sure we need this as dependency or submodule. Will be decided later.
> Move deck-helper to townsquare

- server/game/AbilityTarget.js
- server/game/CardSelectors/BaseCardSelector.js
- server/game/baseability.js
- server/game/cards/DTR/ACoachComesToTown.js
- server/game/gamelocation.js
- server/game/gamesteps/eventwindow.js
- server/game/gamesteps/shootout/shootoutposseprompt.js
- server/game/jobaction.js
- server/game/player.js
- test/helpers/gameflowwrapper.js
- test/helpers/integrationhelper.js
- test/server/card/jobaction.spec.js
- test/server/integration/jobaction.spec.js
Correct some stuff in job action and add special targets for jobs, such as townsquare.
Also added some tests for jobaction.
> Update Job action plus tests

- server/game/Deck.js
- server/game/game.js
- server/game/gamesteps/gamblingphase.js
- server/game/handresult.js
- server/game/jokercard.js
- server/game/player.js
Plus add tie breaking on high cards.
> Implement Jokers

- server/game/GameActions/DiscardCard.js
- server/game/GameActions/PutIntoPlay.js
- server/game/GameActions/Search.js
- server/game/PlayActions/PutIntoPlayCardAction.js
- server/game/basecard.js
- server/game/cards/01-DTR/EveHenry.js
- server/game/cards/01-DTR/IvorHawley.js
- server/game/cards/01-DTR/JiaMein.js
- server/game/cards/01-DTR/KevinWainwright.js
- server/game/cards/01-DTR/Tyxarglenak.js
- server/game/cards/cards_summary.csv
- server/game/effects.js
- server/game/player.js
Jia Mein, Eve Henry, Kevin Wainwright, Ivor Hawley implemented.
Tyxarglenak was started, but will need bigger changes. Since it can be played around I will leave it for later.
> Another 4Ring dudes

- server/game/game.js
- server/game/gamesteps/playwindow.js
- server/game/player.js
Added log messages for move and passing
Removed check for player elimination after empty deck
> Fix issues after first online game

- server/game/cards/01-DTR/ThePharmacy.js
- server/game/cards/01-DTR/YanLisTailoring.js
Implemented The Pharmacy, tested it and it seems to work just fine.
> Implemented The Pharmacy

- server/game/cards/01-DTR/Reserves.js
Reserves works and passes linting.
> Implemented Reserves

- server/game/cards/01-DTR/IrvingPatterson.js
- server/game/cards/04.2-NTB/JacquelineIsham.js
Updated Jacqueline to use traitReaction instead of Reaction, as well as update the game message to go to the message property.
> Implemented Irving Patterson

- server/game/cards/01-DTR/DrDawnEdwards.js
Implemented Dr. Dawn Edwards, and fixed two small typos in Eve Henry's comments (whe > she)
> Implemented Dr. Dawn Edwards

- server/game/cards/01-DTR/FlameThrower.js
- server/game/costs.js
- server/game/costs/XValuePrompt.js
- server/game/effectengine.js
- server/game/effects.js
- server/game/gamesteps/shootout.js
- server/game/player.js
Also fixed small bug when goods after trading was removed from the `cardsInPlay` array of player causing all sorts of problems.
> Card: Flame-Thrower

- docs/cardpool-status.md
- server/game/GhostRockSource.js
- server/game/PlayActions/CustomPlayAction.js
- server/game/basecard.js
- server/game/cardaction.js
- server/game/cards/01-DTR/AutoRevolver.js
- server/game/cards/01-DTR/JamesGhetty.js
- server/game/cards/01-DTR/QuickdrawHandgun.js
- server/game/cards/01-DTR/Shotgun.js
- server/game/cards/04.1-FJ/WinchesterModel1873.js
- server/game/cards/07.3-BadM/LeMatRevolver.js
- server/game/costs.js
- server/game/drawcard.js
- server/game/effects.js
- server/game/gamesteps/shootout/drawhandprompt.js
- server/game/playTypeAbility.js
- server/game/player.js
Updates logic for different GR sources, some small refactor regarding card action and fix for the FLame-Thrower.
> Card: James Ghetty and Auto-Revolver

- server/game/PlayActions/CustomPlayAction.js
- server/game/PlayActions/PutIntoPlayCardAction.js
- server/game/baseability.js
- server/game/basecard.js
- server/game/cardaction.js
- server/game/cards/01-DTR/PinnedDown.js
- server/game/cards/01-DTR/Unprepared.js
- server/game/drawcard.js
- server/game/dudecard.js
- server/game/effects.js
- server/game/gamesteps/shootout/pickyershooterprompt.js
- server/game/gamesteps/shootout/takeyerlumpsprompt.js
- server/game/playTypeAbility.js
- server/game/player.js
- server/game/triggeredability.js
Plus some refactoring regarding `DrawCard.attachments` and ability with playType.
Also fixed small thing in Auto-Revolver.
> Card: Pinned Down and Unprepared

- docs/cardpool-status.md
- server/game/cardaction.js
- server/game/cards/01-DTR/AllieHensman.js
- server/game/cards/01-DTR/CircleMRanch.js
- server/game/cards/01-DTR/JarretBlake.js
- server/game/cards/02.1-NTNR/UlyssesMarks.js
- server/game/cards/04.3-NN/FlintsAmusements.js
Added new properties to card action for If condition and message in case action fails. This is used by cards that have If condition inside the ability.
Example:
> **Shootout**: If Jarrett has a Horse, swap him with one of your dudes in the posse
> Card: Jarret Blake

- docs/cardpool-status.md
- server/game/CardSelector.js
- server/game/cardaction.js
- server/game/cards/11-TCaR/DevilsSixGun.js
- server/game/game.js
- server/game/gamesteps/InterruptWindow.js
- server/game/player.js
- test/server/gamesteps/eventwindow.spec.js
Also changed cardselector.js so that Jokers can be selected by prompts.
> Implemented Devil's Six Gun

- docs/cardpool-status.md
- docs/implementing-cards.md
- server/game/AbilityTarget.js
- server/game/CardMatcher.js
- server/game/CardSelectors/BaseCardSelector.js
- server/game/cards/01-DTR/HaroldAimslee.js
- server/game/cards/01-DTR/RunEmDown.js
- server/game/dudecard.js
- server/game/game.js
- server/game/gamelocation.js
- server/game/gamesteps/selectlocationprompt.js
Updated some card selector stuff to include also townsquare and allowing condition on target.cardCondition
> Card: Run 'Em Down and Harold Aimslee

- server/game/cards/01-DTR/AutoRevolver.js
- server/game/cards/01-DTR/BountyHunter.js
- server/game/cards/01-DTR/MagicalDistraction.js
- server/game/cards/01-DTR/MechanicalHorse.js
- server/game/cards/01-DTR/RemyLaPointe.js
- server/game/cards/02.2-DD/ItsNotWhatYouKnow.js
- server/game/gamesteps/shootout.js
- server/game/player.js
Small fixes for paying of reduceable ghost rock and move options.
> Card: Magical Distraction, Remy LaPointe, Mechanical Horse

- server/game/gamesteps/shootout.js
- server/game/player.js
Make casualties modifiable outside of the `determineWinner` function and allow it to go below zero.
To modify casualties, use `player.modifyCasualties(amount)` function.
> Update casualties tracking

- docs/cardpool-status.md
- server/game/GameActions/Search.js
- server/game/cards/05-IOUF/AncestorSpirit.js
- server/game/cards/05-IOUF/ManySpeakAsOne.js
- server/game/cards/09.2-AGE/SunTouchedRaven.js
- server/game/dudecard.js
- server/game/goodscard.js
- server/game/player.js
Plus fixed a bug when goods were not unbooted when left play.
> Card: Many Speak as One, Sun-Touched Raven

- docs/cardpool-status.md
- server/game/GameActions/SendHome.js
- server/game/cards/04.2-NTB/Rapier.js
- server/game/cards/06-TLS/StrengthOfTheAncestors.js
- server/game/dudecard.js
- server/game/gamesteps/shootout.js
- server/game/goodscard.js
Added melee weapon effect that can be reused and fixed some other small things.
> Card: Strength of the Ancestors, Rapier

- server/game/GameActions/LookAtHand.js
- server/game/cards/04.3-NN/NathanShane.js
- server/game/cards/08-GT/SightBeyondSight.js
- test/server/GameActions/LookAtHand.spec.js
Updated `GameActions.lookAtHand`
> Card: Nathan Shane, Sight Beyond Sight

- server/game/cards/01-DTR/RunEmDown.js
- server/game/drawcard.js
- server/game/dudecard.js
- server/game/game.js
- server/game/goodscard.js
- server/game/player.js
- test/server/player/putintoplay.spec.js
> Gadget dudes inventing

- docs/cardpool-status.md
- server/game/basecard.js
- server/game/cardbeforereaction.js
- server/game/cardinsteadreaction.js
- server/game/cards/03-FF/LayOnHands.js
- server/game/cards/05-IOUF/Natalya.js
- server/game/cards/10-BMR/StevieLyndon.js
- server/game/cardtraitbeforereaction.js
- server/game/cardtraitinsteadreaction.js
- server/game/effects.js
- server/game/game.js
- server/game/gamesteps/ReactionBeforeWindow.js
- server/game/gamesteps/TriggeredAbilityWindowTitles.js
- server/game/gamesteps/upkeepphase.js
- server/game/locationcard.js
- server/game/player.js
- server/game/spell.js
- server/game/spellbeforereaction.js
- test/server/gamesteps/BaseAbilityWindow.spec.js
- test/server/gamesteps/TraitTriggeredAbilityWindow.spec.js
- test/server/gamesteps/TriggeredAbilityWindow.spec.js
- test/server/gamesteps/eventwindow.spec.js
Rename insteadreaction to beforereaction
> Card: Stevie Lyndon, Natalya

- docs/cardpool-status.md
- server/game/cards/03-FF/NicodemusWhateley.js
- server/game/dudecard.js
- server/game/effects.js
- server/game/gamelocation.js
Plus Town Square adjacency fix and also fixed effects that remembered some state.
> Card: Nicodemus Whateley

- docs/cardpool-status.md
- server/game/cards/01-DTR/LucindaLucyClover.js
- server/game/cards/03-FF/MicahRyseExp1.js
- server/game/cards/07.1-DDeeds/KarlOdett.js
- server/game/cards/07.2-FP/MarielLewis.js
- server/game/cards/09.2-AGE/JimHexter.js
- server/game/dudecard.js
- server/game/game.js
- Lucinda "Lucy" Clover
- Micah Ryse (Exp.1)
- Karl Odett
- Mariel Lewis
- Jim Hexter
> Card: Implement some cards

- server/game/basecard.js
- server/game/cardaction.js
- server/game/cards/01-DTR/MicahRyse.js
Include various glyph icons based on the reason why the action is disabled.
> Card menu update

- server/game/cards/05-IOUF/SpiritTrail.js
- server/game/cards/09.2-AGE/OpenWound.js
- server/game/effects.js
- server/game/game.js
- server/game/locationcard.js
- server/game/spell.js
Plus fix for dynamic adjacency effect.
> Card: Spirit Trail, Open Wound

- docs/implementing-cards.md
- server/game/Deck.js
- server/game/basecard.js
- server/game/effect.js
- server/game/effects.js
- test/server/card/basecard.spec.js
- test/server/card/drawcard.getsummary.spec.js
This is to support UI changes that will show card is scripted/unscripted and effects currently affecting the card.
> Add scripted and effect properties to card summary

- server/game/cards/08-GT/OnwardChristianSoldiers.js
- server/game/cards/08-GT/SilentSigil.js
- server/game/effect.js
- server/game/handresult.js
- server/game/player.js
- test/server/effect.spec.js
Plus fix for preventing opponent effects.
> Card: Onward Christian Soldiers, Silent Sigil

- docs/cardpool-status.md
- server/game/cards/03-FF/CaliforniaTaxOffice.js
- server/game/cards/08-GT/NotaryPublic.js
- server/game/cards/08-GT/WaltersCreekDistillery.js
- server/game/effects.js
- server/game/game.js
- server/game/gamesteps/gamblingphase.js
- server/game/gamesteps/upkeepphase.js
- server/game/player.js
Fixes:
- borrowed GR on lowball is returned to bank
- redraw of cards to hand
- small refactor of player GR modify function
> Card: California Tax Office, Walters Creek Distillery

- server/game/chatcommands.js
+ hand-rank
+ join-without-move
+ kung-fu
+ skill-rating
> Another chatcommands

- docs/cardpool-status.md
- server/game/cannotrestriction.js
- server/game/cards/01-DTR/PairOfSixShooters.js
- server/game/cards/01-DTR/Peacemaker.js
- server/game/effect.js
- server/game/effects.js
- test/server/effect.spec.js
Plus fix for the effect playType:
- it is stored when the effect is created, because the ability function always returned it based on the current Play Window
> Card: Peacemaker, Pair of Six-Shooters

- server/game/cards/08-GT/TechnologicalExhibition.js
- server/game/cards/09.2-AGE/SiegeOfTheOrphanage.js
- server/game/drawcard.js
- server/game/effects.js
- server/game/game.js
- server/game/gamesteps/shootout.js
- server/game/gamesteps/shootout/runorgunprompt.js
- server/game/goodscard.js
- server/game/player.js
Implemented new cannot flee and can be invented without booting effects.
> Card: Technological Exhibition, Siege of the Orphanage

- server/game/cards/05-IOUF/NatureSpirit.js
- server/game/cards/07.3-BadM/MotherBearsRage.js
Also updated Nature Spirit to leave play if the callout is refused.
> Implemented Mother Bear's Rage

- server/game/GameActions/PutIntoPlay.js
- server/game/PlayActions/PutIntoPlayCardAction.js
- server/game/cards/02.3-EDS/DrewBeauman.js
- server/game/cards/04.2-NTB/JudgeHarrySomersetExp1.js
- server/game/gamesteps/attachmentprompt.js
- server/game/gamesteps/shootout/shootoutposseprompt.js
- server/game/player.js
Gadget inventing updated: added parameter for the scientist if it is predefined.
> Card: Judge Harry Somerset (Exp.1), Drew Beauman

- docs/cardpool-status.md
- server/game/cards/01-DTR/BBAttorneys.js
> implements B&B Attorneys.

- docs/cardpool-status.md
- server/game/cards/01-DTR/Bobo.js
- server/game/game.js
> implements Bobo.

- docs/cardpool-status.md
- server/game/cards/01-DTR/AbramGrothe.js
> implements Abram Grothe.

- docs/cardpool-status.md
- server/game/cards/01-DTR/Roan.js
fixes #170 
this code has been entirely lifted from [Mechanical Horse](https://github.com/townteki/townsquare/blob/master/server/game/cards/01-DTR/MechanicalHorse.js).
> implements Roan

- server/scripts/implementation-status.js
> corrects deckbuilder domain and fixes path in card URL.

- server/game/gamesteps/sundown/discardtohandsizeprompt.js
- server/game/gamesteps/sundownphase.js
- server/game/player.js
fixes #446 
based on the [discard to meet reserve prompt](https://github.com/throneteki/throneteki/blob/master/server/game/gamesteps/taxation/DiscardToReservePrompt.js) from throneteki.
> adds discard-to-hand-size step to sundown phase.

- docs/cardpool-status.md
- server/game/cards/01-DTR/HiredGuns.js
> implements Hired Guns

- docs/cardpool-status.md
- server/game/cards/11-TCaR/BiltonCollectionAgency.js
- server/game/gamesteps/upkeepphase.js
Implemented Bilton Collection Agency
> Bilton Collection Agency

- server/game/cards/01-DTR/GeneralStore.js
- server/game/cards/02.2-DD/BairdsBuildLoan.js
> Implemented Bairds Build & Loan

- server/game/cards/01-DTR/AbramGrothe.js
> use helper method to discard all cards at once.

- docs/cardpool-status.md
- server/game/cards/01-DTR/MakeTheSmartChoice.js
> implements Make the Smart Choice

- docs/cardpool-status.md
- server/game/cards/01-DTR/TheFourthRing.js
- server/game/cards/03-FF/ChuanJenQi.js
- server/game/cards/10-BMR/DiegoLinares.js
- server/game/player.js
Plus:
- fix for The Fourth Ring
- updated pull events and message to show skill rating for inventing
> Card: Chuan "Jen" Qí, Diego Linares

- server/game/cards/01-DTR/AllieHensman.js
- server/game/cards/01-DTR/BadCompany.js
- server/game/cards/01-DTR/BloodCurse.js
- server/game/cards/01-DTR/CheatinVarmint.js
- server/game/cards/01-DTR/EstablishinWhosinCharge.js
- server/game/cards/01-DTR/IrvingPatterson.js
- server/game/cards/01-DTR/LawrenceBlackwood.js
- server/game/cards/01-DTR/Reserves.js
- server/game/cards/01-DTR/TheSloaneGang.js
- server/game/cards/01-DTR/TheUnionCasino.js
- server/game/cards/02.2-DD/CorporealTwist.js
- server/game/cards/02.3-EDS/HunterProtections.js
- server/game/cards/03-FF/MeetTheNewBoss.js
- server/game/cards/03-FF/NicodemusWhateley.js
- server/game/cards/07.3-BadM/TheOrphanage.js
- server/game/cards/09.2-AGE/TheGomorraGazette.js
- server/game/cards/11-TCaR/BiltonCollectionAgency.js
- server/game/game.js
- server/game/gamesteps/valueprompt.js
- server/game/player.js
Small changes to support UI improvements in the `townsquare-client` and update to value prompt to make it smaller.
refs https://github.com/townteki/townsquare-client/pull/47
> Changes for UI improvements and value prompt

- server/game/basecard.js
- server/game/dudecard.js
- server/game/player.js
- server/game/techniqueaction.js
First part of the Kung Fu implementation. Cannot be tested yet, will be done once at least one Technique card is implemented.
> Kung Fu pull and Technique action

- .vscode/townsquare.code-snippets
- server/game/cardaction.js
- server/game/cards/05-IOUF/RabbitsLunarLeap.js
- server/game/dudecard.js
- server/game/techniqueaction.js
- server/game/techniquecard.js
- test/server/cards/cancreatecards.spec.js
Implementing first Technique card. Without the combo part for now.
> Card: Rabbit's Lunar Leap

- server/game/ServerCommands/DropCommand.js
- server/game/dudecard.js
- server/game/player.js
- added move to the card menu for Dudes
- move done by drag&drop in play area or from the card menu passes the order to the next player
> Mark action as taken after Move

- docs/cardpool-status.md
- server/game/NullEvent.js
- server/game/cards/04.1-FJ/FlightOfTheLepus.js
- server/game/cards/07.2-FP/Outgunned.js
- server/game/cards/12-2T2D/Ricochet.js
- server/game/event.js
- server/game/gamesteps/shootout/shootoutposse.js
Plus small refactor of the shooter attribute of the `ShootoutPosse` class.
> Card: Flight of the Lepus, Outgunned

- docs/cardpool-status.md
- server/game/cards/07.3-BadM/BowieKnife.js
fixes https://github.com/townteki/townsquare/issues/308
cobbled together from what i found in [`AutoRevolver`](https://github.com/townteki/townsquare/blob/master/server/game/cards/01-DTR/AutoRevolver.js)
> implements Bowie Knife

- docs/cardpool-status.md
- server/game/cards/03-FF/PettigrewsPawnshop.js
> implements Pettigrew's Pawnshop.

- server/game/ServerCommands/DropCommand.js
- server/game/cards/01-DTR/Unprepared.js
- server/game/cards/09.1-TCR/CominUpRoses.js
- server/game/dudecard.js
- server/game/gamesteps/playwindow.js
- move from menu gives warning that action was done on opponent's turn
- unprepared message fix
- after unscripted action is played, it should be discarded after clicking on Done
- Comin' up Roses game node crash fix
> Bug fixes after test play

- docs/cardpool-status.md
- server/game/CardSelectors/BaseCardSelector.js
- server/game/GameActions/RemoveFromPosse.js
- server/game/GameActions/index.js
- server/game/cardaction.js
- server/game/cards/01-DTR/JarretBlake.js
- server/game/cards/03-FF/LayOnHands.js
- server/game/cards/04.1-FJ/FlightOfTheLepus.js
- server/game/cards/06-TLS/RabbitsDeception.js
- server/game/cards/07.1-DDeeds/RabbitTakesRevenge.js
- server/game/cards/09.3-TSs/ShiLongPeng.js
- server/game/dudecard.js
- server/game/effects.js
- server/game/gamesteps/abilityresolver.js
- server/game/gamesteps/shootout.js
- server/game/gamesteps/shootout/runorgunprompt.js
- server/game/gamesteps/shootout/shootoutposse.js
- server/game/techniqueaction.js
Introduced new effect for cannot leave the shootout and updated shootout steps (Take Yer Lumps, Run or Gun) accordingly.
Plus some fixes in Kung Fu logic.
> Card: Shi Long Peng, Rabbit Takes Revenge

- docs/cardpool-status.md
- server/game/cards/08-GT/EpidemicLaboratory.js
**work in progress**
fixes #296
> implements Epidemic Laboratory

- docs/cardpool-status.md
- server/game/basecard.js
- server/game/cards/05-IOUF/ZhusFerocity.js
- server/game/cards/05-IOUF/ZhusReward.js
- server/game/costs.js
- server/game/game.js
- server/game/gamesteps/abilityresolver.js
- server/game/techniqueaction.js
Added new effect to boot Kung Fu dude and fixed various bugs in KF ability logic.
> Card: Zhu's Reward, Zhu's Ferocity

- docs/cardpool-status.md
- server/game/cards/07.3-BadM/CliffsNo4Saloon.js
> implements Cliff's #4 Saloon.

- docs/cardpool-status.md
- server/game/cards/07.3-BadM/BaijiuJar.js
> implements Baijiu Jar.

- docs/cardpool-status.md
- server/game/basecard.js
- server/game/cards/06-TLS/WendysTeethkickers.js
- server/game/cards/11-TCaR/JasperStone.js
- server/game/cards/11-TCaR/Raven.js
- server/game/chatcommands.js
- server/game/drawcard.js
- server/game/effects.js
- server/game/gamesteps/shootout.js
- server/game/gamesteps/shootout/shootoutposse.js
- server/game/gamesteps/shootout/shootoutposseprompt.js
- server/game/player.js
- test/server/effects/dynamicbullets.spec.js
This is a tricky one so please test is much as you can.
Also fixed Wendy's Teethkickers and updated shootout posse effects.
> Card: Jasper Stone, Raven

- docs/cardpool-status.md
- server/game/cards/01-DTR/PrescottUtter.js
> implements Prescott Utter.

- docs/cardpool-status.md
- server/game/cards/12-2T2D/PapaMarias.js
fixes https://github.com/townteki/townsquare/issues/546
> implements Papa Marias.

- server/game/chatcommands.js
- server/game/game.js
- server/game/gamesteps/shootout/drawhandprompt.js
- server/game/gamesteps/valueprompt.js
- server/game/techniqueaction.js
- /use should be available for outfit
- joker value selection visible for opponent
- combo selection not working
- add message for discarded cards in shootout (for draw hand)
> Fix more stuff after test play

- server/game/cards/06-TLS/EmreTheTurkishBear.js
- server/game/cards/14-HCWM/GabrielPrior.js
- server/game/gamesteps/jokerprompt.js
- server/game/player.js
Need help figuring out how to end on onPullSuccess OR onPullFail
> Card: Gabriel Prior

- README.md
- docs/cardpool-status.md
- server/game/cards/11-TCaR/AgentProvocateur.js
- server/game/cards/12-2T2D/CurseOfFailure.js
- server/game/chatcommands.js
- server/game/drawcard.js
- server/game/effects.js
- server/game/player.js
Not all of the Agent Provocateur trait is implemented because it is very specific and would require a lot of changes only for this card. Can be done later since it can be worked around.
> Card: Agent Provocateur, Curse of Failure

- docs/cardpool-status.md
- server/game/cards/05-IOUF/RabbitsLunarLeap.js
- server/game/cards/11-TCaR/WangMenWu.js
- server/game/cards/12-2T2D/ImYourHuckleberry.js
- server/game/effects.js
- server/game/game.js
- server/game/gamesteps/shootout/shootoutposse.js
Wang Men Wu's trait is very complicated, and I would say impossible to implement so it will be used generally in technique combos. Anyway, there is actually only one technique implemented (Rabbit's Lunar Leap) that is affected, and another one that is not yet implemented (Great Sage Matching Heaven). Thus I decided to implement Wu's trait directly into the combo condition. It is not ideal, but I am not aware of any other way.
> Card: Wang Men Wu, I'm Your Huckleberry

- docs/cardpool-status.md
- server/game/AttachmentValidityCheck.js
- server/game/basecard.js
- server/game/cards/12-2T2D/MatthewRisingSun.js
- server/game/cards/12-2T2D/XiongWendyChengExp1.js
- server/game/effects.js
- server/game/player.js
- server/game/spellcard.js
Plus fix for the totem attachment validity check.
> Card: Xiong "Wendy" Cheng Exp1, Matthew Rising Sun

- server/game/basecard.js
- server/game/chatcommands.js
- server/game/drawcard.js
- server/game/dudecard.js
- server/game/effect.js
- server/game/effectengine.js
- server/game/effects.js
- server/game/heartscard.js
- server/game/traittriggeredability.js
- test/server/card/cardtraitreaction.spec.js
> Trait and Bonuses blanking

- docs/cardpool-status.md
- server/game/cardaction.js
- server/game/cards/15-W2D/AsNatureAndGodIntended.js
> implements As Nature and God Intended.

- server/game/cards/15-W2D/ReggieMallard.js
> Implemented Reggie Mallard

- server/game/cards/15-W2D/WinnersCircleAuctionHouse.js
- server/game/effects.js
Implemented Winners Circle Auction House and added a dynamicControl function to effects.js
> Implemented Winners Circle

- server/game/cards/15-W2D/TheAngler.js
> The Angler

- server/game/cards/01-DTR/SoulBlast.js
- server/game/cards/06-TLS/RedHorsesTail.js
- server/game/cards/12-2T2D/XiongWendyChengExp1.js
- server/game/cards/13-O4B/LorenaCorbett.js
- server/game/cards/13-O4B/MasonAdler.js
- server/game/cards/14-HCWM/DrDelphiWallis.js
- server/game/dudecard.js
- server/game/effects.js
- server/game/gamesteps/abilityresolver.js
- server/game/gamesteps/shootout/shootoutposseprompt.js
- server/game/jokercard.js
- server/game/player.js
Added required effects and fixed:
- bug where action was not marked as taken in case if condition failed
- bug where +1 was added to the selected joker value
> Card: Lorena Corbett, Mason Adler

- server/game/cards/07.3-BadM/TheOrphanage.js
- server/game/game.js
- server/game/gamesteps/setup/grifterprompt.js
- server/game/gamesteps/setupphase.js
- add Grifter prompt in case there are unscripted ones in starting posse
- fix Orphanage bug
- fix crash in case spectator is looking at a draw hand
> Fix some issues

- server/game/cards/13-O4B/Fort51.js
- server/game/goodscard.js
- server/game/player.js
I fixed a small typo when inventing gadgets so that it says "invents" instead of "invent" and I added the isAtHome() function to goodscards.js so that goodscards can check if they are at home or not. Not sure if that is the best approach of if I should have just added that functionality to the Fort 51 card instead.
> Implemented Fort 51

- server/game/GameActions/index.js
- server/game/drawcard.js
- server/game/effects.js
- server/game/goodscard.js
- server/game/player.js
- server/game/spellcard.js
New effect for maximum influence in one location.
Fixes:
- totems should be allowed to be used by any Shaman
- option to invent without booting should be available also for gadget dudes
- some small doc changes
> Another fixes plus new effect

- server/game/chatcommands.js
- server/game/spellcard.js
Also allows to attach totems to any location card.
> Fix for chatcommand pull crash

- docs/cardpool-status.md
- server/game/cards/14-HCWM/PeteSpence.js
> implements Pete Spence.

- server/game/cards/01-DTR/PointBlank.js
- server/game/cards/04.1-FJ/ShieldOfFaith.js
- server/game/cards/12-2T2D/CampbellHatchBilliardParlor.js
- server/game/cards/13-O4B/JohnnyRingo.js
- server/game/cards/13-O4B/SgtElijahClay.js
- server/game/cards/14-HCWM/RedRiverRoulette.js
- server/game/effects.js
Plus fix for PointBlank.js and updates on the shootout effects.
> Card: Johnny Ringo, Sgt. Elijah Clay

- server/game/cards/07.2-FP/Outgunned.js
- server/game/cards/10-BMR/GreatSageMatchingHeaven.js
- server/game/cards/11-TCaR/FriendsInHighPlaces.js
- server/game/cards/11-TCaR/Raven.js
- server/game/cards/13-O4B/MonomiMiles.js
- server/game/dudecard.js
- server/game/gamesteps/shootout.js
- server/game/gamesteps/shootout/shootoutposse.js
Small refactor to create function for posse stats as it is used in cards quite often.
> Card: Monomi Miles, Great Sage Matching Heaven

- .vscode/townsquare.code-snippets
- docs/cardpool-status.md
- server/game/cards/13-O4B/BirdCageTheater.js
- server/game/cards/13-O4B/CochiseCountyCourthouse.js
- server/game/cards/13-O4B/OfficeOfAncestralAffairs.js
- server/game/costs.js
- server/game/costs/CostBuilder.js
- server/game/gamesteps/shootout.js
Plus update leader cost to select only dudes.
> Card: Cochise County Courthouse, Office of Ancestral Affairs

- server/game/chatcommands.js
> Chatcommand to modify production

- server/game/AbilityTarget.js
- server/game/GameActions/CallOut.js
- server/game/baseability.js
- server/game/cards/01-DTR/ElanderBoldman.js
- server/game/cards/16-DTR2/BioChargedNeutralizer2.js
- server/game/cards/16-DTR2/BuffaloRifle2.js
- server/game/cards/16-DTR2/DecimatorArray2.js
- server/game/cards/16-DTR2/DisgenuineCurrencyPress2.js
- server/game/cards/16-DTR2/FaithfulHound2.js
- server/game/cards/16-DTR2/LaQuema2.js
- server/game/cards/16-DTR2/LeMatRevolver2.js
- server/game/cards/16-DTR2/MechanicalHorse2.js
- server/game/cards/16-DTR2/Shotgun2.js
- server/game/cards/16-DTR2/TinStar2.js
- server/game/costs.js
- server/game/gamesteps/valueprompt.js
Only remaining one is `Yagn's Mechanical Skeleton`
> Update goods cards for new core set

- server/game/cards/16-DTR2/TrickShooting.js
closes townteki/townsquare-ptdt#24
> Card: Trick Shooting

- docs/cardpool-status.md
- server/game/cards/13-O4B/BayouVermilionRailroad.js
- server/game/drawcard.js
- server/game/dudecard.js
- server/game/effects.js
- server/game/gamelocation.js
- server/game/goodscard.js
> Implements Bayou Vermilion Railroad

- server/game/cards/16-DTR2/Bootsie.js
- server/game/cards/16-DTR2/Ruckus.js
- Ruckus
- Bootsie
closes townteki/townsquare-ptdt#12
closes townteki/townsquare-ptdt#13
> Another new cards

- server/game/GameActions/CallOut.js
- server/game/cards/16-DTR2/BassReeves.js
- server/game/cards/16-DTR2/Coyote.js
- server/game/cards/16-DTR2/JessicaPratchett.js
- server/game/cards/16-DTR2/MysteriousAimsSister.js
- server/game/cards/16-DTR2/Werewolf.js
- server/game/costs/CostBuilder.js
- server/game/dudecard.js
- server/game/effects.js
- server/game/player.js
- Bass Reeves
- Coyote (final name will be different)
- Jessica Pratchett
- Mysterious Aims Sister
- Werewolf
closes townteki/townsquare-ptdt#5
closes townteki/townsquare-ptdt#6
closes townteki/townsquare-ptdt#7
closes townteki/townsquare-ptdt#9
closes townteki/townsquare-ptdt#10
> New dude cards

- server/game/cards/11-TCaR/Intercession.js
- server/game/dudecard.js
added events for when a dude becomes a stud or draw
> Implemented Intercession and updated dude.js

- docs/cardpool-status.md
- server/game/cards/13-O4B/CarterRichardson.js
> implements Carter Richardson.

- docs/cardpool-status.md
- server/game/PlayActions/PutIntoPlayCardAction.js
- server/game/PlayActions/ShoppinCardAction.js
- server/game/PlayActions/StandardActions.js
- server/game/ServerCommands/DropCommand.js
- server/game/cards/01-DTR/JiaMein.js
- server/game/cards/01-DTR/Rumors.js
- server/game/cards/02.1-NTNR/TownCouncil.js
- server/game/cards/02.3-EDS/DrewBeauman.js
- server/game/cards/06-TLS/AsakichiCooke.js
- server/game/cards/10-BMR/AmazingGrace.js
- server/game/cards/10-BMR/MorganRegulators.js
- server/game/cards/11-TCaR/EzekiahGrimme.js
- server/game/cards/13-O4B/CarterRichardson.js
- server/game/cards/13-O4B/OfficeOfAncestralAffairs.js
- server/game/cards/16-DTR2/JiaMein2.js
- server/game/cards/16-DTR2/MorganRegulators2.js
- server/game/dudecard.js
- server/game/effects.js
- server/game/game.js
- server/game/gamesteps/gamblingphase.js
- Rumors
- Amazing Grace
- Town Council
- Morgan Regulators
Plus refactor of the drag&drop move action which now goes through the ability resolver and is not a simple game action.
> Various Legacy cards

- docs/cardpool-status.md
- server/game/cards/10-BMR/ChristinePerfect.js
> implements Christine Perfect.

- server/game/nullcard.js
> Add missing functions to NullCard

- docs/cardpool-status.md
- server/game/GameActions/Search.js
- server/game/cards/01-DTR/TravisMoone.js
- server/game/cards/03-FF/FuntimeFreddy.js
- server/game/cards/06-TLS/IvorHawleyExp1.js
- server/game/cards/09.2-AGE/SunTouchedRaven.js
- server/game/player.js
- server/game/triggeredability.js
Plus:
- update grifter react to use property
- refactor Search game action
- update check for unique cards in boot hill in case that card is being put into play
> Card: Funtime Freddy, Ivor Hawley (Exp.1)

- server/game/cards/15-W2D/BaiYangChenExp1.js
- server/game/gamesteps/playwindow.js
- server/game/player.js
- server/game/techniqueaction.js
New Kung Fu rules should replace old ones.
> Update new Kung Fu

- docs/cardpool-status.md
- server/game/cards/11-TCaR/RosenbaumsGolem.js
> implements Rosenbaum's Golem.

- server/game/cards/09.1-TCR/MaggieHarris.js
- server/game/cards/16-DTR2/MaggieHarris2.js
minor language fix, i discovered this issue when i was pilfering Maggie's ability for Grimoires & More (see #805 ).
> language fix.

- server/game/cards/01-DTR/AutoRevolver.js
- server/game/cards/01-DTR/KillerBunniesCasino.js
- server/game/cards/05-IOUF/BaiYangChen.js
- server/game/cards/05-IOUF/Randall.js
- server/game/cards/08-GT/SilentSigil.js
- server/game/cards/11-TCaR/JasperStone.js
- server/game/cards/11-TCaR/MorganLash.js
- server/game/cards/16-DTR2/Randall2.js
- server/game/gamesteps/shootout/drawhandprompt.js
- server/game/player.js
Fix bugs reported in discord:
- `Killer Bunnies Casino` and other deeds do not have the effect matching controller updated
- player can put into play other unique deed if the previous one is controlled by opponent
- it can happen that some cards are not highlighted in the draw hand during the draw hand prompt. This usually happens if player does not have enough cards in deck and need to shuffle his discard into deck.
> Fix some bugs

- docs/cardpool-status.md
- server/game/cards/09.3-TSs/GrimoiresAndMore.js
> implements Grimoires & More

- server/game/gamesteps/gamblingphase.js
- server/game/gamesteps/shootout.js
> Fix lowball bug

- docs/cardpool-status.md
- server/game/basecard.js
- server/game/cards/12-2T2D/HostileTakeover.js
- server/game/cards/14-HCWM/FrontierFeud.js
- server/game/dudecard.js
Plus small fix for Trading action - it now can happen only in a controlled location.
> Card: Hostile Takeover, Frontier Feud

- server/game/cards/01-DTR/Gunslinger.js
- server/game/cards/11-TCaR/Remedy.js
- server/game/cards/11-TCaR/WangMenWu.js
- server/game/gamesteps/shootout.js
- server/game/gamesteps/shootout/pickyershooterprompt.js
- server/game/gamesteps/shootout/shootoutposse.js
- server/game/locationcard.js
- checking if deed is out of town was not working
- Wang Men Wu react triggering on unopposed job
- Remedy not removing stud effects from chat commands
- other small changes
> Fix some bugs after test play

- server/gamenode/gameserver.js
- server/socket.js
Disable Raven until it is properly configured as it is causing game server crashes.
> Disable Raven temporarily

- docs/cardpool-status.md
- server/game/cards/01-DTR/MagicalDistraction.js
- server/game/cards/02.1-NTNR/TheRDRanch.js
- server/game/cards/07.2-FP/XemosTurban.js
- server/game/cards/09.3-TSs/GrimoiresAndMore.js
- server/game/cards/11-TCaR/AdrianVallejo.js
- server/game/cards/12-2T2D/ElectrostaticPumpGun.js
- server/game/cards/13-O4B/RobertoMuratore.js
- server/game/cards/16-DTR2/TrickShooting.js
- server/game/player.js
During the testing I found out the handling of pulled cards in card scripts (such as experimental) is not done properly, or not for all cards. To resolve this, I added new event handler into the `pull` function in `player.js` to handle the pull card every time a context is passed. Therefore the only responsibility card script has is to pass the context.
> Card: Roberto Muratore, Adrian Vallejo

- docs/cardpool-status.md
- server/game/basecard.js
- server/game/cards/04.3-NN/FateDispenser.js
- server/game/cards/05-IOUF/SpiritTrail.js
- server/game/cards/06-TLS/FireOfNanahbozho.js
- server/game/cards/08-GT/OlHoward.js
- server/game/cards/16-DTR2/FireOfNanahbozho2.js
- server/game/drawcard.js
- server/game/effects.js
- server/game/goodscard.js
- server/game/player.js
Bigger change containing handling of Improvement cards and correctly setting controllers for attachments.
> Card: Fate Dispenser, Ol'Howard

- server/gamenode/gameserver.js
- server/gamenode/zmqsocket.js
- server/gamerouter.js
- server/socket.js
Setup Raven to post error reports to Sentry.
> Raven setup for Sentry

- docs/cardpool-status.md
- server/game/basecard.js
- server/game/cards/03-FF/MorganGadgetorium.js
- server/game/cards/07.1-DDeeds/MiasmaticPurifier.js
- server/game/cards/08-GT/WagnerMemorialRanch.js
- server/game/gamesteps/setup/startingposseprompt.js
- server/game/gamesteps/sundownphase.js
- server/game/goodscard.js
- server/game/player.js
Plus small refactor of inventing and fix for Improvement targeting.
> Card: Miasmatic Purifier, Wagner Memorial Ranch

- server/game/cards/03-FF/WilliamSpecks.js
- server/game/cards/07.2-FP/OldMargesManor.js
> Fix some Mad Gadget cards

- server/game/handresult.js
This issue was appearing when hands with 2 different values with multiple cards (two pair, full house).
Those values were not ordered.
> Fix tiebreaker issue

- server/game/CardVisibility.js
- server/game/basecard.js
- test/server/CardVisibility.spec.js
> Fix starting posse visibility

- server/game/cards/08-GT/OlHoward.js
> Fix Ol'Howard

- server/game/cards/14-HCWM/JoanMcGruder.js
> Fix TypeError in JoanMcGruder

- docs/cardpool-status.md
- server/game/cardaction.js
- server/game/cards/09.2-AGE/DoomsdaySupply.js
- server/game/cards/09.3-TSs/Pedro.js
- server/game/cards/11-TCaR/BuffaloEmporium.js
- server/game/costs.js
Added `discardSelf` cost and updated card action requirements to allow to trigger also abilities on goods attached to home.
> Card: Pedro, Doomsday Supply

- server/game/chatcommands.js
> Do not allow /done and /pass on Gamblin'

- server/game/chatcommands.js
- server/game/game.js
- server/game/gamesteps/basestep.js
- server/game/gamesteps/playwindow.js
- server/game/gamesteps/shootout.js
- server/game/gamesteps/shootout/drawhandprompt.js
- server/game/gamesteps/shootout/pickyershooterprompt.js
- server/game/gamesteps/shootout/runorgunprompt.js
- server/game/gamesteps/shootout/shootoutorderprompt.js
- server/game/gamesteps/shootout/takeyerlumpsprompt.js
- server/gamenode/gameserver.js
Added `/debug-dump` command to manually trigger TypeError that will report back with game info.
> Fix cancel shootout chatcommand

- server/game/player.js
> Fix Gadget deeds inventing

- docs/cardpool-status.md
- server/game/cards/10-BMR/GomorraGamingCommission.js
* Adding file for Gomorra Gaming Commission
* Marking Gomorra Gaming Commission
> Card: BMR - Gomorra Gaming Commission

- server/game/cards/02.3-EDS/ElectionDaySlaughter.js
> Fix TypeError in ElectionDaySlaughter

- docs/cardpool-status.md
- server/game/cards/04.2-NTB/SecuredStockyard.js
* Adding file for Secured Stockyard
* Marking Secured Stockyard
> Card: NTB - Secured Stockyard

- docs/cardpool-status.md
- server/game/cards/01-DTR/MarionSeville.js
* Added file for Marion Seville
* Marking Marion Seville
> Card: DTR - Marion Seville

- docs/cardpool-status.md
- server/game/cards/01-DTR/FredAims.js
- server/game/cards/01-DTR/SilasAims.js
* Adding files for Fred and Silas
* Marking Fred and Silas
> Card:Fred & Silas Aims

- server/game/PropertyTypes/KeywordsProperty.js
- server/game/drawcard.js
- server/game/dudecard.js
- server/game/effect.js
- server/game/player.js
> Fix Experienced dudes upgrading

- server/game/CardVisibility.js
> Make draw hand visible to spectators

- server/game/cards/01-DTR/Kidnappin.js
- server/game/cards/12-2T2D/Heist.js
- server/game/cards/13-O4B/CochiseCountyCourthouse.js
- server/game/cards/13-O4B/OfficeOfAncestralAffairs.js
- server/game/costs.js
- server/game/costs/BootCost.js
- server/game/costs/SelectCardCost.js
- server/game/gamesteps/basestep.js
- server/game/gamesteps/shootout.js
- server/game/gamesteps/shootout/shootoutposseprompt.js
- server/game/jobaction.js
> Job posse conditions

- docs/cardpool-status.md
- server/game/cards/13-O4B/WyattEarp.js
- server/game/cards/14-HCWM/JonahEssexExp1.js
- server/game/game.js
> Card: Wyatt Earp, Jonah Essex (Exp.1)

- server/game/GameActions/DiscardTopCards.js
- server/game/GameActions/DrawCards.js
- server/game/GameActions/LookAtDeck.js
- server/game/GameActions/PlaceToken.js
- server/game/cards/01-DTR/BottomDealin.js
- server/game/cards/07.3-BadM/ArnoldStewart.js
- server/game/cards/08-GT/HenryMoran.js
- server/game/event.js
- server/game/player.js
- test/server/Event.spec.js
- test/server/GameActions/DrawCards.spec.js
- test/server/GameActions/LookAtDeck.spec.js
- test/server/GameActions/PlaceToken.spec.js
- test/server/player/drawDeckAction.spec.js
> Update Draw Deck action

- docs/cardpool-status.md
- server/game/cards/02.1-NTNR/TooMuchAttention.js
- server/game/cards/10-BMR/GreatSageMatchingHeaven.js
- server/game/cards/10-BMR/TwoHundredFiftyRounds.js
- server/game/cards/16-DTR2/TooMuchAttention2.js
- server/game/cards/16-DTR2/TwoHundredFiftyRounds.js
- server/game/techniqueaction.js
Plus some small changes and fix for combo condition which was not checked.
> Card: Too Much Attention, Two Hundred Fifty Rounds

- docs/cardpool-status.md
- server/game/cards/08-GT/MahoganyJackson.js
- server/game/cards/10-BMR/ThunderBoyNabbe.js
- server/game/cards/13-O4B/MasonAdler.js
- server/game/cards/16-DTR2/MahoganyJackson2.js
- server/game/cards/16-DTR2/ThunderBoyNabbe2.js
> Card: "Mahogany" Jackson, "Thunder Boy" Nabbe

- server/game/triggeredability.js
- test/server/card/cardreaction.spec.js
- test/server/card/cardtraitreaction.spec.js
> Fix Reacts and traits during setup

- server/game/cards/16-DTR2/DeborahWestExp1.js
- server/game/cards/16-DTR2/UrsulaTheWormQueen.js
Closes townteki/townsquare-ptdt#29
Closes townteki/townsquare-ptdt#34
> Card: Deborah West Exp.1, Ursula the Worm Queen

- docs/cardpool-status.md
- server/game/cards/01-DTR/WhiskeyFlask.js
* Adding file for Whiskey Flask
* Marking Whiskey Flask
> Whiskey Flask

- server/game/cards/01-DTR/MechanicalHorse.js
- server/game/cards/16-DTR2/NewTownHall.js
- server/game/cards/16-DTR2/RaggedMule.js
- server/game/costs/DiscardFromPlayCost.js
closes townteki/townsquare-ptdt#26
closes townteki/townsquare-ptdt#28
> Card: Ragged Mule, New Town Hall

- docs/cardpool-status.md
- server/game/cards/04.2-NTB/AsyncoilGun.js
* Adding file for Asyncoil Gun
* Marking Asyncoil Gun
> Card: NTB - Asyncoil Gun

- server/game/basecard.js
- server/game/drawcard.js
- server/game/dudecard.js
- server/game/effects.js
Plus fix for the value modification.
fixes #940
> Fix stats reset when leaving play

- server/game/GameActions/JoinPosse.js
- server/game/gamesteps/shootout.js
> Update Breakin' and Enterin' bounties

- docs/cardpool-status.md
- server/game/cards/01-DTR/FirstBaptistChurch.js
* Adding file for 1st Baptist Church
* Marking 1st Baptist Church
> Card: DTR - 1st Baptist Church

- docs/cardpool-status.md
- server/game/cards/01-DTR/PistolWhip.js
- server/game/cards/02.3-EDS/RiddenDown.js
- server/game/cards/06-TLS/RabbitsDeception.js
- server/game/cards/07.1-DDeeds/PersonalOrnithopter.js
- server/game/cards/07.2-FP/MarielLewis.js
- server/game/cards/11-TCaR/Censure.js
- server/game/cards/11-TCaR/ChargingBear.js
- server/game/cards/12-2T2D/OldWashoeClub.js
- server/game/cards/12-2T2D/SilasAimsExp1.js
- server/game/cards/12-2T2D/XiongWendyChengExp1.js
- server/game/cards/13-O4B/DancingButterfly.js
- server/game/cards/13-O4B/DrGregoryTremane.js
- server/game/cards/14-HCWM/SeizingThePearlOfDeath.js
- server/game/cards/16-DTR2/RiddenDown2.js
Plus game action update for all cards that are sending home booted.
> Card: Ridden Down

- server/game/cards/16-DTR2/AlfredByrne.js
- server/game/cards/16-DTR2/LandonGrimes.js
closes townteki/townsquare-ptdt#3
closes townteki/townsquare-ptdt#4
> Card: Alfred Byrne, Landon Grimes

- docs/cardpool-status.md
- server/game/cards/09.1-TCR/TheHighbinderHotel.js
* Adding file for The Highbinder Hotel
* Marking The Highbinder Hotel
Went with the Pistol Whip method.
> Card: TCR - The Highbinder Hotel

- docs/cardpool-status.md
- server/game/cards/03-FF/DesolationRow.js
- server/game/gamesteps/shootout.js
Plus small refactor of the Job ending.
> Card: Desolation Row

- server/game/Constants/Factions.js
- server/game/cards/06-TLS/IvorHawleyExp1.js
- server/game/cards/07.1-DDeeds/ZacharyDeloria.js
- server/game/cards/08-GT/WagnerMemorialRanch.js
- server/game/cards/11-TCaR/MorganLash.js
- server/game/cards/11-TCaR/ZebWhateleyDupont.js
- server/game/cards/13-O4B/DrGregoryTremane.js
- server/game/cards/13-O4B/WyattEarp.js
- server/game/cards/14-HCWM/JonahEssexExp1.js
- server/game/cards/16-DTR2/BassReeves.js
- server/game/cards/16-DTR2/EBFarnum.js
- server/game/cards/16-DTR2/EagleWomanThatAllLookAt.js
- server/game/cards/16-DTR2/HaoTeZui.js
- server/game/cards/16-DTR2/JessicaPatchett.js
- server/game/cards/16-DTR2/UrsulaTheWormQueen.js
- server/game/cards/16-DTR2/ZacharyDeloria2.js
- server/game/player.js
closes townteki/townsquare-ptdt#1
closes townteki/townsquare-ptdt#2
> Card: E.B.Farnum, Hao-T’e Zui

- server/game/cards/16-DTR2/LauraBanks.js
- server/game/cards/16-DTR2/PoliteInquiries.js
- server/game/cards/16-DTR2/SilverWeavedStaff.js
- server/game/player.js
closes townteki/townsquare-ptdt#38
closes townteki/townsquare-ptdt#39
closes townteki/townsquare-ptdt#40
> Card: Polite Inquiries, Laura Banks, Silver-Weaved Staff

- server/game/cards/07.1-DDeeds/RabbitTakesRevenge.js
- server/game/cards/16-DTR2/CrushingInevitability.js
- server/game/cards/16-DTR2/RabbitsSweepingSnare.js
- server/game/gamesteps/shootout/shootoutposse.js
Also fix for the effect preventing dudes to contribute to draw hands.
closes townteki/townsquare-ptdt#41
closes townteki/townsquare-ptdt#42
> Card: Crushing Inevitability, Rabbit's Sweeping Snare

- server/game/basecard.js
- server/game/game.js
> Remove default card boot/unboot

- docs/cardpool-status.md
- server/game/cards/02.3-EDS/QUATERMAN.js
* Adding file for QUATERMAN
* Marking QUATERMAN
> Card: EDS - QUATERMAN

- server/game/GameActions/DiscardCard.js
- server/game/gamesteps/upkeep/upkeepprompt.js
- server/game/player.js
- test/helpers/gameflowwrapper.js
> Update Upkeep discard prompt

- docs/cardpool-status.md
- server/game/cards/01-DTR/GomorraParish.js
* Adding file for Gomorra Parish
* Marking Gomorra Parish
> Card: DTR - Gomorra Parish

- server/game/cards/14-HCWM/VirgilEarp.js
- server/game/gamesteps/selectcardprompt.js
- server/game/gamesteps/setup/startingposseprompt.js
- server/game/gamesteps/shootout/drawhandprompt.js
- server/game/gamesteps/shootout/takeyerlumpsprompt.js
- server/game/gamesteps/upkeep/upkeepprompt.js
- server/game/playerpromptstate.js
UI part: townteki/townsquare-client#89
> Create Info area in player prompt

- docs/cardpool-status.md
- server/game/cards/01-DTR/XiongWendyCheng.js
* Adding file for Xiong Wendy Cheng
* Marking Xiong Wendy Cheng
> Card: DTR - Xiong Wendy Cheng

- docs/cardpool-status.md
- server/game/cards/04.1-FJ/BennyMcGill.js
* Adding file for Benny McGill
* Marking Benny McGill
> Card: FJ - Benny McGill

- server/game/cards/01-DTR/TheSloaneGang.js
- server/game/cards/08-GT/FoolMeOnce.js
- server/game/dudecard.js
* bounty/bullets lookup fix
Fixes Curly Bill Brocius
* message fix
It referred to the outfit already
* card condition update
must boot the dude
> Misc fixes

- docs/cardpool-status.md
- server/game/cards/12-2T2D/Skinwalker.js
- server/game/gamesteps/shootout/shootoutposse.js
> implements Skinwalker

- server/scripts/fetchclient.js
> Remove dtts.online

- server/game/cards/01-DTR/ShadowWalk.js
> Fix Shadow Walk

- server/game/gamesteps/gamblingphase.js
> Add message for Lowball ante

- server/game/cards/01-DTR/BartonEverest.js
- server/game/cards/01-DTR/CheatinVarmint.js
- server/game/cards/01-DTR/ForceField.js
- server/game/cards/01-DTR/HexSlingin.js
- server/game/cards/01-DTR/MagicalDistraction.js
- server/game/cards/01-DTR/TommyHarden.js
- server/game/cards/02.2-DD/ItsNotWhatYouKnow.js
- server/game/cards/07.2-FP/Outgunned.js
- server/game/cards/07.3-BadM/LeMatRevolver.js
- server/game/cards/11-TCaR/Censure.js
- server/game/cards/11-TCaR/TheWinningAgenda.js
- server/game/cards/12-2T2D/Bedazzle.js
- server/game/cards/12-2T2D/RangersBible.js
- server/game/cards/14-HCWM/VirgilEarp.js
- server/game/cards/15-W2D/MissedMe.js
- server/game/cards/15-W2D/PlayForBlood.js
- server/game/cards/16-DTR2/BakerAndrews.js
- server/game/cards/16-DTR2/BassReeves.js
- server/game/cards/16-DTR2/LeMatRevolver2.js
- server/game/player.js
> Refactor rank modification

- server/game/cards/04.3-NN/FlintsAmusements.js
- test/server/cards/cancreatecards.spec.js
> Fix FlintsAmusements.js

- server/game/automaton.js
- server/game/game.js
- server/game/player.js
- server/game/spectator.js
> Solo: Automaton skeleton

- server/game/automaton.js
- server/game/game.js
- server/gamenode/gameserver.js
- server/lobby.js
- server/pendinggame.js
> Solo: Initialization of Automaton

- docs/cardpool-status.md
- server/game/cards/02.2-DD/LeonardoLeonCavallo.js
* Adding file for Leonardo Cavallo
* Marking Leonardo Cavallo
With thanks to Papa Marias, Arden Gillman and Blood Curse
closes #853
> Card: DD - Leonardo Cavallo

- server/game/gamesteps/ChooseYesNoPrompt.js
- server/game/gamesteps/menuprompt.js
- server/game/gamesteps/selectcardprompt.js
- server/game/gamesteps/valueprompt.js
This is temporary change until Decision Engine is implemented.
> Update prompts to have player decide for Automaton

- server/game/Solo/Archetypes/GunfighterArchetype.js
Also discard down to hand size limit.
> Solo: Automaton pull - Use ability

- server/game/Solo/Archetypes/BaseArchetype.js
- server/game/Solo/Archetypes/GunfighterArchetype.js
- server/game/Solo/automaton.js
- server/game/Solo/priorities.js
- server/game/basecard.js
- server/game/cards/01-DTR/JarretBlake.js
- server/game/cards/01-DTR/Pinto.js
- server/game/cards/01-DTR/ShadowWalk.js
- server/game/cards/02.2-DD/AngelicaEspinosa.js
- server/game/cards/04.2-NTB/LaQuema.js
- server/game/cards/09.3-TSs/GhostlyCommunion.js
- server/game/cards/14-HCWM/HarlanStanton.js
- server/game/cards/16-DTR2/BuffaloRifle2.js
- server/game/cards/16-DTR2/GhostlyCommunion2.js
- server/game/cards/16-DTR2/LaQuema2.js
- server/game/cards/16-DTR2/ShadowWalk2.js
- server/game/drawcard.js
- server/game/game.js
- server/game/gamesteps/shootout.js
Plus prevent rest from the pull steps from executing in case shootout was started.
> Solo: Target priorities when forming posse

- server/game/player.js
> Update Kung Fu based on final rules

- server/game/cards/16-DT2/SavedByGrace.js
- server/game/cards/16-DT2/SunInYerEyes2.js
> Update WWE: Saved By Grace, Sun In Yer Eyes

- server/game/cards/03-FF/MeetTheNewBoss.js
- server/game/cards/16-DT2/DeadwoodMinersAlliance.js
- server/game/cards/16-DT2/MeetTheNewBoss2.js
- server/game/cards/16-DT2/OlFashionedHangin2.js
Plus small update for Ol' Fashioned Hanging'
part of #1343
> Update WWE: Deadwood Miners Alliance, Meet the New Boss

- server/game/cards/07.2-FP/XemosTurban.js
- server/game/cards/16-DT2/JimHexter2.js
- server/game/cards/16-DT2/LaneHealey2.js
- server/game/cards/16-DT2/MirandaClarke2.js
- server/game/cards/16-DT2/ShiLongPeng2.js
- Xemo's Turban - make pull a cost
- Jim Hexter - use repeatable limit ability property
- Lane Healey - add -1 upkeep effect
- Miranda Clarke - change influence bonus to +1
- Shi Long Peng - remove trait
part of #1343
> Update WWE: Various cards

- server/game/cards/01-DTR/Kidnappin.js
- server/game/cards/16-DT2/Belligerence.js
- server/game/cards/16-DT2/Kidnappin2.js
- server/game/cards/16-DT2/TheMixer2.js
Fixes code for Belligerence
part of #1118 
part of #1343
> Update WWE: Kidnappin', The Mixer

- docs/cardpool-status.md
- server/game/cards/05-IOUF/ManySpeakAsOne.js
- server/game/cards/14-HCWM/AncestorsReproach.js
- server/game/cards/16-DT2/AncestorSpirit2.js
- server/game/cards/16-DT2/Gunslinger2.js
- server/game/cards/16-DT2/ManySpeakAsOne2.js
- server/game/player.js
> Update WWE: Tokens and cardpool

- server/game/cards/16-DT2/Kidnappin2.js
- server/game/cards/16-DT2/SavedByGrace.js
> Fix WWE Kidnappin' and Saved by Grace

- server/game/cards/09.2-AGE/OpenWound.js
- server/game/cards/11-TCaR/NightmareRealm.js
- server/game/cards/13-O4B/JohnnyRingo.js
- server/game/cards/16-DT2/108GraciousGifts2.js
- server/game/cards/16-DT2/CallingTheCavalry2.js
- server/game/cards/16-DT2/EmreTheTurkishBearExp1.js
- server/game/cards/16-DT2/ZacharyDeloria2.js
- server/game/drawcard.js
- server/game/game.js
- server/game/player.js
fixes #1355 
fixes #1358
fixes #1356
> Various fixes not just for WWE

- server/game/basecard.js
- server/game/cards/05-IOUF/YunxuJiang.js
- server/game/cards/07.1-DDeeds/JaelsGuile.js
- server/game/cards/09.2-AGE/TheMixer.js
- server/game/cards/11-TCaR/NightmareRealm.js
- server/game/cards/16-DT2/PoliteInquiries.js
- server/game/cards/16-DT2/TheMixer2.js
- server/game/cards/16-DT2/WalterJameson.js
- server/game/effects.js
- server/game/game.js
- server/game/gamesteps/abilityresolver.js
- server/game/gamesteps/highnoon/tradingprompt.js
- server/game/outfitcard.js
- server/game/player.js
- server/game/techniqueaction.js
- test/server/player/putintoplay.spec.js
- cancelling of KF dude resulted in Type Error
- trading allowed to booted dude
- various card fixes
- card piles not properly managed if card controlled by payer other then owner left play
> Another fixes not just for WWE

- server/game/cards/16-DT2/YagnsMechanicalSkeleton2.js
- server/game/dudecard.js
- server/game/gamesteps/upkeepphase.js
- server/game/player.js
Fixed cards:
- Yagn's Mechanical Skeleton
- Bottom Dealin'
> Fix some cards and upkeep when borrowed

- server/game/gamesteps/sundown/discardprompt.js
- server/game/gamesteps/upkeep/upkeepprompt.js
- server/game/player.js
> Fix Discard and Upkeep prompt issues

- server/game/cards/02.1-NTNR/MakeEmSweat.js
- server/game/cards/05-IOUF/RakingDragons.js
- server/game/cards/05-IOUF/ZhusFerocity.js
- server/game/player.js
Plus small clarity fix in Make 'Em Sweat
> Fix techniques with target used in combo

- server/game/cards/10-BMR/HydroPuncher.js
- server/game/cards/12-2T2D/KevinWainwrightExp1.js
- server/game/cards/13-O4B/MasonAdler.js
- server/game/effects.js
Plus message update for Hydro Puncher.
> Fix Kevin Wainwright and Mason Adler

- server/game/cards/14-HCWM/MarshalCavesCallarman.js
- server/game/cards/16-DT2/CallingTheCavalry2.js
- server/game/cards/16-DT2/RaggedMule.js
- server/game/cards/16-DT2/YagnsMechanicalSkeleton2.js
- server/game/gamesteps/nightfall/discardprompt.js
- Marshal Caves Callarman - public condition did not count with TS
- Calling the Cavalry - wrong message for WWE version
- Ragged Mule - TypeError - incorrect function on array
- Yagn's Mechanical Skeleton - asked for react even when returning from job
- Lacy O'Malley - cards not discarded during Nightfall
> Another batch of fixes

- server/game/cards/15-W2D/Benediction.js
> Fix Benediction.js

- server/game/cards/02.2-DD/BairdsBuildLoan.js
- server/game/cards/14-HCWM/ViveneGoldsun.js
- server/game/cards/15-W2D/NuttalMannsNo10Saloon.js
- server/game/cards/16-DT2/TheMixer2.js
- server/game/dudecard.js
- Nuttal & Mann's No. 10 Saloon - missing shootout
- upgrading dudes clears bounty
- Baird's Build & Loan - incorrect controller for target
- The Mixer - incorrect opponent
- Vivene Goldsun - small text fixes
fixes #1376
> Fix another bugs

- server/game/game.js
- server/game/timeLimit.js
ui part: townteki/townsquare-client#112
> Add time panel

- server/game/nullcard.js
Add default implementation of isNearby() to NullCard since some cards will attempt to call it.
> Update NullCard with isNearby()

- server/game/cards/16-DT2/LayOnHands2.js
- server/game/cards/16-DT2/ThirstForBlood.js
- server/game/gamesteps/shootout.js
Plus small refactor for Lay on Hands (WWE)
> Fix Thirst for Blood and forming posses event

- test/server/GameActions/DiscardTopCards.spec.js
Brings overall coverage for this class to 80%
> Unit tests for DiscardTopCards.js

- server/game/GameActions/LookAtHand.js
- server/game/MathHelper.js
- server/game/game.js
- server/game/gamesteps/setupphase.js
- server/game/player.js
- test/server/game/getplayers.spec.js
> Random first player on setup

- server/game/cards/01-DTR/RamiroMendoza.js
- server/game/drawcard.js
- server/game/dudecard.js
- server/game/game.js
- server/game/gamesteps/upkeep/upkeepprompt.js
- server/game/player.js
- server/game/timeLimit.js
Fix Ramiro Mendoza to ask to pay 1 GR, timer start and cards with upkeep other than dudes.
> Some fixes

- server/game/GameActions/AddBounty.js
- server/game/GameActions/JoinPosse.js
- server/game/GameActions/MoveBounty.js
- server/game/GameActions/index.js
- server/game/cards/01-DTR/Ambush.js
- server/game/cards/10-BMR/BurnEmOut.js
- server/game/cards/13-O4B/JonahsAlliance.js
- server/game/gamesteps/shootout.js
> Use GameAction to increase bounty

- docs/cardpool-status.md
- server/game/cards/02.1-NTNR/TelepathyHelmet.js
* Adding file for Telepathy Helmet
* Marking Telepathy Helmet
> Card: NTNR - Telepathy Helmet

- docs/cardpool-status.md
- server/game/cards/03-FF/OutlawMask.js
* Adding file for Outlaw Mask
* Marking Outlaw Mask
> Card: FF - Outlaw Mask

- docs/cardpool-status.md
- server/game/cards/04.1-FJ/TheFlyingPopescus.js
* Adding file for The Flying Popescus
* Marking The Flying Popescus
> Card: FJ - The Flying Popescus

- docs/cardpool-status.md
- server/game/cards/09.3-TSs/GamblersGun.js
* Adding file for The Gambler's Gun
* Marking The Gambler's Gun
(Perhaps Fiddle Game and this could log what card caused the trigger)
> Card: TS - The Gambler's Gun

- docs/cardpool-status.md
- server/game/cards/01-DTR/SanfordTaylor.js
* Adding file for Sanford Taylor
* Marking Sanford Taylor
> Card: DTR - Sanford Taylor

- docs/cardpool-status.md
- server/game/cards/02.1-NTNR/BackWays.js
* Adding file for Back Ways
* Marking Back Ways
> Card: NTNR - Back Ways

- docs/cardpool-status.md
- server/game/cards/02.2-DD/TallulahLulaMorgan.js
* Adding file for Tallulah Morgan
* Marking Tallulah Morgan
> Card: DD - Tallulah Morgan

- server/game/cardaction.js
- server/game/cards/09.1-TCR/PuttingThePiecesTogether.js
- server/game/cards/13-O4B/TestOfWills.js
- server/game/cards/16-DT2/BassReeves.js
- server/game/cards/16-DT2/LauraBanks.js
- server/game/cards/16-DT2/QuickdrawHandgun2.js
- server/game/cards/16-DT2/RaggedMule.js
- server/game/handresult.js
* Removing unfinished message
Full message is already in changeBountyLaura()
* Fixing ref count
It counted 0, 2, 3
* Typo
looses -> loses
* PlayType fix
Ability was unusable
* Update handresult.js
Heretic joker can beat up Devils joker (If both present, cheatness depended on which joker was rightmost in the hand)
* Fix Type Error in case shootout gets into weird state
* Fix Putting the Pieces Together to not require action cost when it is in play
part of #1412
> Misc fixes 2

- docs/cardpool-status.md
- server/game/cards/01-DTR/MongwauTheMighty.js
- server/game/cards/09.3-TSs/GeneNorthStar.js
* Adding file for Gene North Star
* Marking Gene North Star
> Card: TSs - Gene North Star

- docs/cardpool-status.md
- server/game/cards/09.3-TSs/TheGreyMan.js
* Adding file for The Grey Man
* Marking The Grey Man
> Card: TSs - The Grey Man

- docs/cardpool-status.md
- server/game/cards/05-IOUF/TouChiChow.js
* Adding file for T'ou Chi Chow
* Marking T'ou Chi Chow
Speed challenge to code a card before the game it's used in is over. Success if this passes checks.
> Card: IOUF - Tou Chi Chow

- docs/cardpool-status.md
- server/game/cards/01-DTR/ProfEustaceTrue.js
* Adding file for Eustace True
* Marking Eustace True
> Card: DTR - Prof. Eustace True

- docs/cardpool-status.md
- server/game/cards/02.2-DD/StoneIdol.js
* Adding file for Stone Idol
* Marking Stone Idol
> Card: DD - Stone Idol

- docs/cardpool-status.md
- server/game/cards/07.3-BadM/LukeTheErrandBoy.js
* Added file for Luke, the Errand Boy
* Marking Luke, the Errand Boy
> Card: BadM - Luke, the Errand Boy

- docs/cardpool-status.md
- server/game/cards/04.3-NN/OldManMcDroste.js
* Adding file for Old Man McDroste
* Marking Old Man McDroste
> Card: NN - Old Man McDroste

- docs/cardpool-status.md
- server/game/cards/07.1-DDeeds/DrBrianFoxworth.js
* Adding file for Dr. Brian Foxworth
* Marking Dr. Brian Foxworth
> Card: DDeeds - Dr. Brian Foxworth

- docs/cardpool-status.md
- server/game/cards/01-DTR/MaxBaine.js
* Adding file for Max Baine
* Marking Max Baine
> Card: DTR - Max Baine

- server/game/cards/01-DTR/FlameThrower.js
- server/game/cards/01-DTR/PearlHandledRevolver.js
- server/game/cards/03-FF/BioChargedNeutralizer.js
- server/game/cards/04.2-NTB/LaQuema.js
- server/game/cards/04.2-NTB/Rapier.js
- server/game/cards/07.1-DDeeds/TlalocsFuries.js
- server/game/cards/07.3-BadM/BowieKnife.js
- server/game/cards/11-TCaR/DevilsSixGun.js
- server/game/cards/12-2T2D/Claws.js
- server/game/cards/14-HCWM/BlueLightnin.js
- server/game/cards/16-DT2/BioChargedNeutralizer2.js
- server/game/gamesteps/shootout/shootoutposseprompt.js
- server/game/heartscard.js
> Fix stud blanking issue and others

- docs/cardpool-status.md
- server/game/cards/02.3-EDS/TeleportationDevice.js
* Adding file for Teleportation Device
* Marking Teleportation Device
> Card: EDS - Teleportation Device

- server/game/cards/04.3-NN/SteeleArcherExp1.js
* Adding file for Steele Archer (Exp.1)
Should already be marked
Total rush job; blatant JonLongstride copy, hence the `&& card.booted`
> Card: NN - Steele Archer (Exp.1)

- server/game/cards/13-O4B/RobertoMuratore.js
> Fix Roberto Muratore

- docs/cardpool-status.md
- server/game/cards/01-DTR/BottomDealin.js
- server/game/cards/04.2-NTB/CookinUpTrouble.js
- server/game/cards/04.3-NN/SoulCage.js
- server/game/cards/08-GT/FranciscoRosales.js
- server/game/cards/10-BMR/ChristinePerfect.js
- server/game/cards/13-O4B/BigNoseKate.js
- server/game/chatcommands.js
* Issues tackled
#1426, task 2 and task 6
closes #1427
closes #1436
* Fixes bug with Soul Cage seen in stream
* Fixes Bottom Dealin' logging bug seen in stream
* Update chatcommands.js
RemoveFromGame may target jokers
* Update cardpool-status.md
Moving Funtime Freddy to correct pack
> Random Fixes 4

- server/game/player.js
- test/server/player/canattach.spec.js
> Fix attaching improvements

- server/game/gamesteps/shootout.js
> Fix sending home after job

- server/game/cards/14-HCWM/BogieMan.js
- server/game/player.js
> Fix Bogie Man

- server/game/cards/01-DTR/HaroldAimslee.js
> Fix Harold Aimslee

- server/game/player.js
> Fix inventing gadget dudes

- server/game/cards/07.1-DDeeds/MorganStables.js
> Fix Morgan Stables

- server/game/cards/16-DT2/BakerAndrews.js
- server/game/drawcard.js
- server/game/game.js
Fixes:
- Baker Andrews bounty
- double CP count on attachments
- falling off of attachments in case parent was blanked
closes #1411
> Fix some nitpicky stuff

- docs/cardpool-status.md
- server/game/cards/01-DTR/LadyLuck.js
* Adding file for Lady Luck
* Marking Lady Luck
> Card: DTR - Lady Luck

- server/game/cards/05-IOUF/SpiritTrail.js
> WWE Spirit Trail not providing adjacency

- docs/cardpool-status.md
- server/game/cards/07.2-FP/MartyrsCry.js
* Adding file for Martyr's Cry
* Marking Martyr's Cry
> Card: FP - Martyr's Cry

- docs/cardpool-status.md
- server/game/cards/04.1-FJ/LegalInstruments.js
* Adding file for Legal Instruments
* Marking Legal Instruments
> Card: FJ - Legal Instruments

- docs/cardpool-status.md
- server/game/cards/03-FF/UnderTheWeather.js
* Adding file for Under the Weather
* Marking Under the Weather
> Card: FF - Under the Weather

- server/game/GameActions/PutIntoPlay.js
- server/game/PlayActions/PutIntoPlayCardAction.js
- server/game/ServerCommands/DropCommand.js
- server/game/cards/15-W2D/JohnAcesRadcliffeExp1.js
- server/game/player.js
- test/helpers/playerinteractionwrapper.js
> Do not invent when dropping gadget into play

- server/game/gamesteps/shootout.js
Not exactly following the sequence as they are defined in the rules, but at least moves leader posse to mark before opponent decides if they are going to oppose.
part of #1467
> Update job posse forming

- server/game/gamesteps/shootout/drawhandprompt.js
- server/game/handresult.js
- server/game/player.js
> Fix when not enough cards to make draw hand

- server/api/account.js
- server/models/User.js
UI part: townteki/townsquare-client#164
> Add Discord chat widget

- server/game/GameActions/AceCard.js
- server/game/cards/13-O4B/ByronDecker.js
> Fix Byron Decker

- server/game/player.js
> Do not invent when reattaching in game

- server/game/GameActions/MoveDude.js
- server/game/gamesteps/shootout.js
- test/server/integration/jobaction.spec.js
> Update dudes leaving posse after job

- server/game/PlayActions/PutIntoPlayCardAction.js
- server/game/cards/01-DTR/LawrenceBlackwood.js
- server/game/cards/07.1-DDeeds/DisgenuineCurrencyPress.js
- server/game/cards/08-GT/NotaryPublic.js
- server/game/cards/10-BMR/NickelNightInn.js
- server/game/cards/13-O4B/OfficeOfAncestralAffairs.js
- server/game/cards/14-HCWM/Crystal Palace.js
- server/game/cards/16-DT2/DisingenuineCurrencyPress2.js
- server/game/cards/16-DT2/MountMoriahCemetery.js
- server/game/spellcard.js
> Fixes for minor bugs

- server/game/playTypeAbility.js
> Prevent action to play in any window

- server/game/game.js
closes #996 
ui part: townteki/townsquare-client#167
> Add Keep Selected button to draw hand

- server/game/basecard.js
ui part: townteki/townsquare-client#168
closes #962
> Add support for filtering buttons in UI

- server/game/cards/16-DT2/FarnumsConsortium.js
> Fix FarnumsConsortium.js

- server/game/cards/14-HCWM/FrontierFeud.js
> Update Frontier Feud menu options

- server/game/basecard.js
- server/game/gamelocation.js
- server/game/nullcard.js
- server/game/townsquarecard.js
> Refactor card hierarchy + TownSquare card

- server/game/basecard.js
> Reset abilities when leaving play

- server/game/cards/08-GT/EpidemicLaboratory.js
> Fix Epidemic Laboratory leader requirement

- server/game/gamesteps/shootout/takeyerlumpsprompt.js
- server/game/player.js
- test/helpers/DeckBuilder.js
- test/helpers/Hands.js
- test/helpers/gameflowwrapper.js
- test/server/integration/takeyerlumps.spec.js
ui part: townteki/townsquare-client#170
closes #207
> Take Yer Lumps step improvement

- server/game/PlayActions/PutIntoPlayCardAction.js
> Fix PutIntoPlay action reduction stacking

- server/game/drawcard.js
- server/game/dudecard.js
- server/game/gamelocation.js
- server/game/gamesteps/ChooseYesNoPrompt.js
- server/game/gamesteps/shootout.js
- server/log.js
UI part: townteki/townsquare-client#181
closes #1533
> Add job mark information and highlight

- server/game/Message.js
- server/game/PlainTextGameChatFormatter.js
- server/game/basecard.js
- server/game/cards/01-DTR/Rumors.js
- server/game/cards/04.3-NN/SwordOfTheSpirit.js
- server/game/cards/07.3-BadM/TheOrphanage.js
- server/game/cards/09.1-TCR/CominUpRoses.js
- server/game/cards/13-O4B/Malison.js
- server/game/cards/13-O4B/Scattergun.js
- server/game/cards/13-O4B/TwilightIsUponUs.js
- server/game/cards/15-W2D/LewisGrizzlyEvans.js
- server/game/cards/16-DT2/FireOfNanahbozho2.js
- server/game/cards/16-DT2/SwordOfTheSpirit2.js
- server/game/drawcard.js
- server/game/effect.js
- server/game/effectengine.js
- server/game/effects.js
- server/game/gamesteps/shootout.js
- server/game/player.js
- test/server/Message.spec.js
- test/server/card/basecard.spec.js
- test/server/card/drawcard.attachments.spec.js
- test/server/card/drawcard.getsummary.spec.js
- test/server/cards/cancreatecards.spec.js
UI part: townteki/townsquare-client#183
> Implement Effects in UI

- server/game/cards/01-DTR/HidingInTheShadows.js
- server/game/cards/01-DTR/TheSloaneGang.js
- server/game/cards/07.3-BadM/WillaMaeMacGowan.js
- server/game/cards/10-BMR/ChristinePerfect.js
- server/game/cards/13-O4B/BayouVermilionRailroad.js
- server/game/cards/14-HCWM/Crystal Palace.js
Various fixes,
incl. point 6 of #1517
> GroutAndSpackle2

- server/game/cards/01-DTR/BuffaloRifle.js
- server/game/cards/02.2-DD/AngelicaEspinosa.js
- server/game/cards/04.1-FJ/ShaneGravesSecurity.js
- server/game/cards/09.2-AGE/SiegeOfTheOrphanage.js
- server/game/cards/09.3-TSs/GhostlyCommunion.js
- server/game/cards/11-TCaR/AdrianVallejo.js
- server/game/cards/11-TCaR/JasperStone.js
- server/game/cards/11-TCaR/Raven.js
- server/game/game.js
- server/game/gamelocation.js
- server/game/gamesteps/shootout.js
- server/game/nulllocation.js
> Add nulllocation to return if no shootout location

- server/game/gamesteps/shootout.js
UI part: townteki/townsquare-client#187
> Add cheatin' info to shootout panel

- server/game/cards/06-TLS/Enapay.js
- server/game/cards/06-TLS/IvorHawleyExp1.js
- server/game/cards/11-TCaR/HellstrommePlant9.js
- server/game/cards/11-TCaR/RosenbaumsGolem.js
- server/game/cards/12-2T2D/108GraciousGifts.js
- server/game/cards/15-W2D/Vamoosin.js
- server/game/cards/16-DT2/108GraciousGifts2.js
- server/game/cards/16-DT2/BioChargedNeutralizer2.js
- server/game/cards/16-DT2/FireOfNanahbozho2.js
- server/game/drawcard.js
- test/server/player/movecard.spec.js
Fixes stuff from #1517 
plus fixing Vamoosin as it was not able to play for this from other GR sources (e.g. Old Marge's Manor)
> Fixes for nitpicking bugs

- server/game/GameActions/JoinPosse.js
Dude is booted when joining job posse using card effects.
> Fix joining job posse

- server/game/gamesteps/shootout/takeyerlumpsprompt.js
> Fix first casualty bug

- server/game/cards/01-DTR/PinnedDown.js
> Fix PinnedDown.js

- server/game/cards/09.3-TSs/CallingTheCavalry.js
- server/game/cards/16-DT2/CallingTheCavalry2.js
> Fix Calling the Cavalry

- server/game/cards/07.3-BadM/TheOrphanage.js
> Fix The Orphanage

- server/game/gamesteps/shootout/shootoutposseprompt.js
- test/server/integration/jobaction.spec.js
> Add warning if no dude selected to oppose
